ALTER TABLE BBB_MEETING ADD (RECORDING CHAR(1));
ALTER TABLE BBB_MEETING ADD (RECORDING_DURATION INT);
ALTER TABLE BBB_MEETING ADD (VOICE_BRIDGE NUMBER(5));
ALTER TABLE BBB_MEETING ADD (DELETED NUMBER(1));
ALTER TABLE BBB_MEETING ADD (WAIT_FOR_MODERATOR CHAR(1));
ALTER TABLE BBB_MEETING ADD (MULTIPLE_SESSIONS_ALLOWED CHAR(1));
ALTER TABLE BBB_MEETING CHANGE (HOST_URL CHAR(255));
