ALTER TABLE BBB_MEETING ADD RECORDING CHAR(1);
ALTER TABLE BBB_MEETING ADD RECORDING_DURATION INT DEFAULT 0;
ALTER TABLE BBB_MEETING ADD VOICE_BRIDGE INT;
ALTER TABLE BBB_MEETING ADD DELETED INT DEFAULT 0; 
