ALTER TABLE BBB_MEETING ADD (RECORDING CHAR(1));
ALTER TABLE BBB_MEETING ADD (RECORDING_DURATION NUMBER(10) DEFAULT 0);
ALTER TABLE BBB_MEETING ADD (VOICE_BRIDGE NUMBER(5));
ALTER TABLE BBB_MEETING ADD (DELETED NUMBER(1) DEFAULT 0);
