ALTER TABLE BBB_MEETING ADD COLUMN RECORDING CHAR(1) AFTER END_DATE;
ALTER TABLE BBB_MEETING ADD COLUMN RECORDING_DURATION INT DEFAULT 0 AFTER RECORDING;
ALTER TABLE BBB_MEETING ADD COLUMN VOICE_BRIDGE INT AFTER RECORDING_DURATION;
ALTER TABLE BBB_MEETING ADD COLUMN DELETED INT DEFAULT 0 AFTER PROPERTIES;
