ALTER TABLE BBB_MEETING ADD COLUMN RECORDING BOOLEAN AFTER END_DATE;
ALTER TABLE BBB_MEETING ADD COLUMN RECORDING_DURATION INT AFTER RECORDING;
ALTER TABLE BBB_MEETING ADD COLUMN DELETED INT(1) NOT NULL DEFAULT '0' AFTER PROPERTIES;